# ----------------------------------------------------------------------------------
#  Copyright (c) Microsoft Corporation.
#  Licensed under the MIT license.
#  THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
#  EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
#  OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

# Pipeline Decorators build & publish pipeline
# Builds the extension, increments the patch number, and publishes the extension.
# https://aka.ms/yaml

parameters:
  - name: ManifestFile
    type: string
    displayName: Extension manifest file
    default: 'vss-extension.json'

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  # Group defines variables: $(PersonalAccessToken), $(ShareWithOrgs)
  # 'PersonalAccessToken' is an Azure DevOps PAT with full Marketplace access
  # 'ShareWithOrgs' is a comma-separated list of Azure DevOps orgs to share the extension with
  - group: pipeline-decorators-variables
    
stages:
- stage:
  jobs:
  - job:
    steps:

    - checkout: self
      clean: true
      persistCredentials: true

    - task: PowerShell@2
      name: InstallTools
      displayName: 'Install tools'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Installing tools..."
          npm install -g typescript
          npm install -g tfx-cli

    - task: PowerShell@2
      displayName: 'Increment version'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Incrementing patch number..."
          $manifest = (Get-Content -Raw ${{ parameters.ManifestFile }} | ConvertFrom-Json -Depth 100)
          $version = $manifest.version
          $versionParts = $version.Split('.')
          $versionParts[2] = [string]([int]$versionParts[2] + 1)
          $manifest.version = $versionParts -join '.'
          $manifest | ConvertTo-Json -Depth 100 | Set-Content ${{ parameters.ManifestFile }}

    - task: PowerShell@2
      displayName: 'Package extension'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Packaging extension..."
          tfx extension create --manifests ${{ parameters.ManifestFile }}

    - task: PowerShell@2
      displayName: 'Publish extension'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Publishing extension..."
          $PackageFile = (Get-ChildItem -Filter '*.vsix' -File)[0].Name
          Write-Output "Package file: $PackageFile"
          tfx extension publish --auth-type pat --token $(PersonalAccessToken) --manifests ${{ parameters.ManifestFile }} --vsix $PackageFile --share-with $(ShareWithOrgs)
    
    - task: PowerShell@2
      displayName: 'Commit changes'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Committing changes..."
          git config --global user.email "nomail@contoso.com"
          git config --global user.name "Azure Pipelines"
          git add ${{ parameters.ManifestFile }}
          git commit -m "Incremented patch number [skip ci]"
          git push origin HEAD:$(Build.SourceBranchName)

