#
# 1. Install the Azure DevOps Extension Tasks from the Visual Studio Marketplace.
# https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks&targetId=85fb3d5a-9f21-420f-8de3-fc80bf29054b&utm_source=vstsproduct&utm_medium=ExtHubManageList
#
# 2. Follow steps in "Create a build and release pipeline to publish the extension to Marketplace".
# https://learn.microsoft.com/azure/devops/extend/develop/add-build-task?view=azure-devops#6-create-a-build-and-release-pipeline-to-publish-the-extension-to-marketplace
#
# Publish from the command line:
# https://learn.microsoft.com/azure/devops/extend/publish/command-line
#
# tfx reset --all
#
# Issues with publishing from the command line:
# https://github.com/microsoft/vsmarketplace/discussions/161
#
# Running Git commands in a pipeline:
# https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands
#

parameters:
  - name: ManifestFile
    type: string
    displayName: Extension manifest file
    default: 'vss-extension.json'

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  # Group defines variables: $(PersonalAccessToken), $(ShareWithOrgs)
  # 'PersonalAccessToken' is an Azure DevOps PAT with full Marketplace access
  # 'ShareWithOrgs' is a comma-separated list of Azure DevOps orgs to share the extension with
  - group: pipeline-decorators-variables
    
stages:
- stage:
  jobs:
  - job:
    steps:

    - checkout: self
      clean: true
      persistCredentials: true

    - task: PowerShell@2
      name: InstallPackages
      displayName: 'Install packages'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Installing packages..."
          npm install -g typescript
          npm install -g tfx-cli

    # - task: PowerShell@2
    #   name: GetVariables
    #   displayName: 'Get variables'
    #   inputs:
    #     pwsh: true
    #     targetType: 'inline'
    #     script: |
    #       $publisherId = (Get-Content ${{ parameters.ManifestFile }} | jq -r '.publisher')
    #       $extensionId = (Get-Content ${{ parameters.ManifestFile }} | jq -r '.id')
    #       $extensionName = (Get-Content ${{ parameters.ManifestFile }} | jq -r '.name')
    #       $version = (Get-Content ${{ parameters.ManifestFile }} | jq -r '.version')
    #       $outputPath = $publisherId + '.' + $extensionId + '-' + $version + '.vsix'
    #       Write-Host "##vso[task.setvariable variable=PublisherId]$publisherId"
    #       Write-Host "##vso[task.setvariable variable=ExtensionId]$extensionId"
    #       Write-Host "##vso[task.setvariable variable=ExtensionName]$extensionName"
    #       Write-Host "##vso[task.setvariable variable=Version]$version"
    #       Write-Host "##vso[task.setvariable variable=OutputPath]$outputPath"
    #     # workingDirectory: '$(System.DefaultWorkingDirectory)'

    # - task: PowerShell@2
    #   displayName: 'Get extension details'
    #   inputs:
    #     pwsh: true
    #     targetType: 'inline'
    #     script: |
    #       # Write-Host "##vso[task.setvariable variable=ExtensionPackageFile]$($PublisherId).$($ExtensionId)-$$(Version).vsix"

    #       $extensionDetailsJson = (tfx extension show --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token $(PersonalAccessToken) --publisher '$(PublisherId)' --extension-id '$(ExtensionId)')


    #       if ($extensionDetailsJson -ne 'null') {
    #         Write-Output $extensionDetailsJson

    #         $extensionDetails = ($extensionDetailsJson | ConvertFrom-Json -Depth 100)
    #         # Write-Host "##vso[task.setvariable variable=ExtensionVersion]$($extensionDetails.versions[0].version)"
    #       } else {
    #         Write-Output "No extension details found"
    #         Write-Host "##vso[task.setvariable variable=ExtensionVersion]0.0.0"
    #       }
    #     # workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: PowerShell@2
      displayName: 'Increment patch number'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Incrementing patch number..."
          $manifest = (Get-Content -Raw ${{ parameters.ManifestFile }} | ConvertFrom-Json -Depth 100)
          $version = $manifefst.version
          $versionParts = $version.Split('.')
          $versionParts[2] = [string]([int]$versionParts[2] + 1)
          $manifest.version = $versionParts -join '.'
          $manifest | ConvertTo-Json -Depth 100 | Set-Content ${{ parameters.ManifestFile }}

    - task: PowerShell@2
      displayName: 'Package extension'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Packaging extension..."
          tfx extension create --manifests ${{ parameters.ManifestFile }}

    - task: PowerShell@2
      displayName: 'Publish extension'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Publishing extension..."
          $PackageFile = ((Get-ChildItem -Filter '*.vsix' -File).Name)[0]
          Write-Output "Package file: $PackageFile"
          tfx extension publish --auth-type pat --token $(PersonalAccessToken) --manifests ${{ parameters.ManifestFile }} --vsix $PackageFile --share-with $(ShareWithOrgs)
    
    - task: PowerShell@2
      displayName: 'Commit changes'
      inputs:
        pwsh: true
        targetType: 'inline'
        script: |
          Write-Output "Committing changes..."
          git config --global user.email "nomail@contoso.com"
          git config --global user.name "Azure Pipelines"
          git add ${{ parameters.ManifestFile }}
          git commit -m "Incremented patch number [skip ci]"
          git push origin HEAD:$(Build.SourceBranchName)


    # - task: QueryAzureDevOpsExtensionVersion@4
    #   name: Query
    #   inputs:
    #     connectTo: 'VsTeam'
    #     connectedServiceName: $(ServiceConnection)
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     # extensionTag: '$(ExtensionTag)'
    #     versionAction: 'Patch'
    #     # output variable: $(Query.Extension.Version)

    # - task: PowerShell@2
    #   condition: failed()
    #   displayName: 'Show extension version'
    #   inputs:
    #     pwsh: true
    #     targetType: 'inline'
    #     script: |
    #       Write-Output "$(Query.Extension.Version)"

    # - task: PowerShell@2
    #   displayName: 'Show extension version'
    #   inputs:
    #     pwsh: true
    #     targetType: 'inline'
    #     script: |
    #       Write-Output "$(Query.Extension.Version)"


#====================================================================================================

    # - task: PackageAzureDevOpsExtension@4
    #   inputs:
    #     rootFolder: 
    #     patternManifest: '${{ parameters.ExtensionManifestFile }}'
    #     outputPath: 'GeneratedVsix.vsix'
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     updateTasksVersion: false

    # - task: PublishAzureDevOpsExtension@4
    #   inputs:
    #     connectTo: 'VsTeam'
    #     connectedServiceName: 'VisualStudioMarketplace'
    #     fileType: 'vsix'
    #     vsixFile: 'GeneratedVsix.vsix'
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     extensionTag: '$(ExtensionTag)'
    #     extensionName: '$(ExtensionName)'
    #     extensionVersion: '$(ExtensionVersion)'
    #     extensionVisibility: 'private'
    #     extensionPricing: 'free'
    #     shareWith: '$(ShareWithOrgs)'
    #     noWaitValidation: true
    #     cwd: '$(System.DefaultWorkingDirectory)'

    # - task: IsAzureDevOpsExtensionValid@4
    #   inputs:
    #     connectTo: 'VsTeam'
    #     connectedServiceName: 'VisualStudioMarketplace'
    #     method: 'id'
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     extensionTag: '$(ExtensionTag)'
    #     extensionVersion: '$(ExtensionVersion)'
    #     minTimeout: '5'

    # - task: UnpublishAzureDevOpsExtension@4
    #   inputs:
    #     connectTo: 'VsTeam'
    #     connectedServiceName: 'VisualStudioMarketplace'
    #     method: 'id'
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     extensionTag: '$(ExtensionTag)'
    #     arguments: '$(Args)'
    #     cwd: '$(WorkingDir)'
  
  
#====================================================================================================


    # - task: PowerShell@2
    #   displayName: 'Build extension'
    #   inputs:
    #     pwsh: true
    #     targetType: 'inline'
    #     script: |
    #       Write-Host "##vso[task.setvariable variable=ExtensionId]$(Get-Content ${{ parameters.ExtensionManifestFile }} | jq -r '.id')"
    #       Write-Host "##vso[task.setvariable variable=Version]$(Get-Content ${{ parameters.ExtensionManifestFile }} | jq -r '.version')"
    #       Write-Host "##vso[task.setvariable variable=PublisherId]$(Get-Content ${{ parameters.ExtensionManifestFile }} | jq -r '.publisher')"
    #       Write-Host "##vso[task.setvariable variable=ExtensionPackageFile]$($publisher).$($id)-$$(version).vsix"

    #       npx tfx-cli extension create --manifest-globs ${{ parameters.ExtensionManifestFile }} --output-path $output
    #     workingDirectory: '$(System.DefaultWorkingDirectory)'

    # - task: PowerShell@2
    #   displayName: 'Set extension version'
    #   inputs:
    #     pwsh: true
    #     targetType: 'inline'
    #     script: |
    #       $version = $(Get-Content ${{ parameters.ExtensionManifestFile }} | jq -r '.version')
    #       $version = $version.Split('.')
    #       $version[2] = $version[2] + 1
    #       $version = $version -join '.'

    #       Write-Host "##vso[task.setvariable variable=Version]$version"
    #       Write-Host "##vso[task.setvariable variable=ExtensionPackageFile]$($publisher).$($id)-$$(version).vsix"

    #       $manifest = Get-Content ${{ parameters.ExtensionManifestFile }} | ConvertFrom-Json
    #       $manifest.version = $version
    #       $manifest | ConvertTo-Json -Depth 100 | Set-Content ${{ parameters.ExtensionManifestFile }}

    #       $diff = ([DateTime]::Now - [DateTime]::Parse("2023-06-01"))
    #       $diff.ToString()

    
    # - task: PackageAzureDevOpsExtension@4
    #   displayName: 'Package extension'
    #   inputs:
    #     # rootFolder: 
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     updateTasksVersion: false
    
    # - task: PublishAzureDevOpsExtension@4
    #   displayName: 'Publish extension'
    #   inputs:
    #     connectTo: 'VsTeam'
    #     connectedServiceName: 'VisualStudioMarketplace'
    #     fileType: 'vsix'
    #     vsixFile: '$output'
    #     publisherId: '$(PublisherId)'
    #     extensionId: '$(ExtensionId)'
    #     extensionName: '$(ExtensionName)'
    #     updateTasksVersion: false
    #     extensionVisibility: 'private'
    #     extensionPricing: 'free'
    #     shareWith: '$(ShareWithOrgs)'
    #     noWaitValidation: true

